# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Select', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('delivery_charge', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField()),
                ('isveg', models.BooleanField(default=True)),
                ('num', models.IntegerField()),
                ('isavailable', models.BooleanField(default=True)),
                ('genre', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='kaizing.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('items', jsonfield.fields.JSONField(default={})),
                ('order_state', models.CharField(choices=[(b'Placed', b'Placed'), (b'Acknowledged', b'Acknowledged'), (b'Completed', b'Completed'), (b'Cancelled', b'Cancelled'), (b'Dispatched', b'Dispatched')], default=b'Placed', max_length=100)),
                ('order_total', models.FloatField(default=0)),
                ('fulfillment_mode', models.CharField(choices=[(b'delivery', b'delivery'), (b'pickup', b'pickup')], default=b'delivery', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaizing.location')),
            ],
        ),
        migrations.CreateModel(
            name='timeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_limit', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=10)),
                ('description', models.TextField(default=b'')),
                ('location', models.TextField(default=b'')),
                ('delivery_time', models.DurationField(default=60)),
                ('tax', models.IntegerField(null=True)),
                ('username', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(blank=True, max_length=10)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaizing.timeSlot'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to='kaizing.Vendor'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='kaizing.Vendor'),
        ),
        migrations.AddField(
            model_name='genre',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='kaizing.Vendor'),
        ),
    ]
